name: flutter_triple
description: Implementation of the Segmented State Pattern (SSP) nicknamed Triple.
version: 1.2.8-dev.1
publish_to: 'none'

repository: https://github.com/Flutterando/triple_pattern/tree/master/stores/flutter_triple
issue_tracker: https://github.com/Flutterando/triple_pattern/issues
homepage: https://triple.flutterando.com.br/
documentation: https://triple.flutterando.com.br/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  rx_notifier:
    git: https://github.com/icarohs7/rx_notifier
  triple:
    git:
      path: triple
      url: https://github.com/icarohs7/triple_pattern

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutterando_analysis: ^0.0.1

# dependency_overrides:
#   triple: 
#     path: ../triple

flutter:
